# POST http://localhost:8080/api/v1/patient
# Content-Type: application/json

# {
#     "uhid": 3, 
#     "samid": 9999, 
#     "rchid": 4566, 
#     "name": "Bharath",
#     "dob": "2018-03-09",
#     "contactno": "8310672772",
#     "gender": "M", 
#     "bpl": false, 
#     "address": "China",
#     "religion": "Hindu", 
#     "symptoms": "None"
# }

PUT http://localhost:8080/api/v1/patient/1?name=Alex
Content-Type: application/json